services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    environment:
      - TZ=Asia/Tokyo
    tty: true
    stdin_open: true
    command: /bin/bash
    depends_on:
      - redis-service

  redis-service:
    image: redis:alpine
    environment:
      - TZ=Asia/Tokyo