services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prd
    environment:
      - TZ=Asia/Tokyo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - "8000:8000"
    depends_on:
      - redis-service

  redis-service:
    image: redis:alpine
    environment:
      - TZ=Asia/Tokyo